// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/brands" | "/client/[token]" | "/dashboard" | "/dashboard/[brandId]" | "/dashboard/[brandId]/competitors" | "/dashboard/[brandId]/insights" | "/dashboard/[brandId]/screenshots" | "/dashboard/[brandId]/settings" | "/dashboard/new" | "/evidence/[checkId]" | "/unauthorized"
type AppRouteHandlerRoutes = "/api/brands" | "/api/brands/[brandId]/ads/[adId]/status" | "/api/brands/[brandId]/check" | "/api/brands/[brandId]/checks/[checkId]/status" | "/api/cron/ahrefs-metrics" | "/api/cron/auction-insights" | "/api/cron/cleanup-screenshots" | "/api/cron/serp-check" | "/api/digest/[brandId]" | "/api/evidence/[checkId]/cease-desist" | "/api/evidence/[checkId]/pdf" | "/api/health" | "/api/test-screenshot"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard/[brandId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/brands": {}
  "/api/brands": {}
  "/api/brands/[brandId]/ads/[adId]/status": { "brandId": string; "adId": string; }
  "/api/brands/[brandId]/check": { "brandId": string; }
  "/api/brands/[brandId]/checks/[checkId]/status": { "brandId": string; "checkId": string; }
  "/api/cron/ahrefs-metrics": {}
  "/api/cron/auction-insights": {}
  "/api/cron/cleanup-screenshots": {}
  "/api/cron/serp-check": {}
  "/api/digest/[brandId]": { "brandId": string; }
  "/api/evidence/[checkId]/cease-desist": { "checkId": string; }
  "/api/evidence/[checkId]/pdf": { "checkId": string; }
  "/api/health": {}
  "/api/test-screenshot": {}
  "/client/[token]": { "token": string; }
  "/dashboard": {}
  "/dashboard/[brandId]": { "brandId": string; }
  "/dashboard/[brandId]/competitors": { "brandId": string; }
  "/dashboard/[brandId]/insights": { "brandId": string; }
  "/dashboard/[brandId]/screenshots": { "brandId": string; }
  "/dashboard/[brandId]/settings": { "brandId": string; }
  "/dashboard/new": {}
  "/evidence/[checkId]": { "checkId": string; }
  "/unauthorized": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard/[brandId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
