// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/brands/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/brands">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/brands/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/client/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/client/[token]">> = Specific
  const handler = {} as typeof import("../../../src/app/client/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/[brandId]/competitors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[brandId]/competitors">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/[brandId]/competitors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/[brandId]/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[brandId]/insights">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/[brandId]/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/[brandId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[brandId]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/[brandId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/[brandId]/screenshots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[brandId]/screenshots">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/[brandId]/screenshots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/[brandId]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[brandId]/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/[brandId]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/new">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/evidence/[checkId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/evidence/[checkId]">> = Specific
  const handler = {} as typeof import("../../../src/app/evidence/[checkId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../../src/app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/brands/[brandId]/ads/[adId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brands/[brandId]/ads/[adId]/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/brands/[brandId]/ads/[adId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/brands/[brandId]/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brands/[brandId]/check">> = Specific
  const handler = {} as typeof import("../../../src/app/api/brands/[brandId]/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/brands/[brandId]/checks/[checkId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brands/[brandId]/checks/[checkId]/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/brands/[brandId]/checks/[checkId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/brands/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/brands">> = Specific
  const handler = {} as typeof import("../../../src/app/api/brands/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/ahrefs-metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/ahrefs-metrics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/ahrefs-metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/auction-insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/auction-insights">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/auction-insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/cleanup-screenshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/cleanup-screenshots">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/cleanup-screenshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/serp-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/serp-check">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/serp-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/digest/[brandId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/digest/[brandId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/digest/[brandId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/evidence/[checkId]/cease-desist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/[checkId]/cease-desist">> = Specific
  const handler = {} as typeof import("../../../src/app/api/evidence/[checkId]/cease-desist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/evidence/[checkId]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evidence/[checkId]/pdf">> = Specific
  const handler = {} as typeof import("../../../src/app/api/evidence/[checkId]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/test-screenshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-screenshot">> = Specific
  const handler = {} as typeof import("../../../src/app/api/test-screenshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/dashboard/[brandId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/[brandId]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/[brandId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
